// AssemblyInfoExtra.cs
//
// Auto-generated by ZXVersion.exe

using System.Reflection;

[assembly: AssemblyConfiguration("8413dfd")]
[assembly: AssemblyCopyright("Copyright © 2019-2025 Robin Verhagen-Guest")]
[assembly: AssemblyVersion("1.8.0.0")]
[assembly: AssemblyFileVersion("1.8.0.0")]
