// AssemblyInfoExtra.cs
//
// Auto-generated by ZXVersion.exe

using System.Reflection;

[assembly: AssemblyConfiguration("7cab4c1")]
[assembly: AssemblyCopyright("Copyright © 2019-2024 Robin Verhagen-Guest")]
[assembly: AssemblyVersion("1.7.0.0")]
[assembly: AssemblyFileVersion("1.7.0.0")]
