// AssemblyInfoExtra.cs
//
// Auto-generated by ZXVersion.exe

using System.Reflection;

[assembly: AssemblyConfiguration("7e20a6b")]
[assembly: AssemblyCopyright("Copyright © 2019-2024 Robin Verhagen-Guest")]
[assembly: AssemblyVersion("1.6.0.0")]
[assembly: AssemblyFileVersion("1.6.0.0")]
